version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-ml-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - mlflow_artifacts:/app/mlflow_artifacts
    depends_on:
      - mlflow
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: ml-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mlflow_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mlflow:
    image: python:3.11-slim
    container_name: mlflow-ui
    command: >
      bash -c "
        pip install mlflow psycopg2-binary &&
        mlflow server 
          --backend-store-uri postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-mlflow_db}
          --default-artifact-root /mlflow/artifacts
          --host 0.0.0.0
          --port 5000
      "
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  mlflow_artifacts: